name: adapter-email

services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  app:
    build:
      context: .
      dockerfile: ../../Dockerfile
      target: dev
    command: ["npx", "tsx", "src/index.ts"]
    environment:
      EMAIL_PROVIDER: "smtp"
      SMTP_HOST: mailhog
      SMTP_PORT: "1025"
      PORT: "3000"
    ports:
      - "3000:3000"
    depends_on:
      - mailhog
